# Matt Edwards Production Campaign with Pre-Scraped Jobs
# Uses job file to avoid SSL/API issues

name: "Matt Edwards - Production Campaign (With Job File)"

applicant:
  first_name: "Matt"
  last_name: "Edwards"
  email: "edwardsdmatt@gmail.com"
  phone: "404-680-8472"
  location: "Atlanta, GA"
  linkedin_url: "https://www.linkedin.com/in/matt-edwards-/"
  years_experience: 5
  clearance: "Secret"
  custom_answers:
    salary_expectations: "$100,000 - $130,000"
    notice_period: "2 weeks"
    willing_to_relocate: "No"
    work_authorization: "US Citizen"

resume:
  path: "data/matt_edwards_resume.pdf"

# Use pre-scraped jobs instead of API search
job_file: "campaigns/kent_le_real_jobs_1000.json"

search:
  roles:
    - "Software Engineer"
  locations:
    - "Remote"

platforms:
  - workday
  - greenhouse

limits:
  max_applications: 10
  max_per_platform: 5
  min_match_score: 0.6

settings:
  auto_submit: false
  delay_between_applications: [30, 60]
  retry_attempts: 3
  enable_iteration: true
  enable_monitoring: true

output:
  dir: "./campaign_output/matt_edwards"
  save_screenshots: true
  generate_report: true
